### ISSUE TITLE
Siglus devkit

### ISSUE THREAD

**Issue by Cosetto** [2439905184/Galgame-Engine-Collect#36]
https://github.com/imKota/SiglusEngineOfficialKit I'm not sure if this is the sdk or not

**Comment by 2439905184** [comment]
> https://github.com/imKota/SiglusEngineOfficialKit I'm not sure if this is the sdk or not

maybe for Translation or patch

**Comment by 2439905184** [comment]
> https://github.com/imKota/SiglusEngineOfficialKit I'm not sure if this is the sdk or not

siglus sdk is close source

**Comment by 2439905184** [comment]
Later to add this

**Comment by 2439905184** [comment]
I think because if this is really offical sdk then this people need to think a lot of things .
He may is the  member of company : 'key' or someone like ceo ?
key company is one of the 合作者或者子公司 of Visual arts company in Japan.
And I think you know this engine is they made by themslefs.
One of their old galgame engine has been open to every to use .
(But seems not opensource and have technology support )

**Comment by Cosetto** [comment]
I'm not sure where did he get this from but he said he also has the source code, and the kit is compiled from the source code

**Comment by 2439905184** [comment]
We do not need to care this too much , I just want to archive them (like what the museum does)

**Comment by imKota** [comment]
@2439905184 hello! Can you please delete this issue and [引擎下载](https://github.com/imKota/SiglusEngineOfficialKit) from readme?
